'''Vocab lists stored as dictionaries in the format of

    "<English translation>" : "<Japanese word/phrase>"

        or

    "<English translation>" : ["<hiragana>", "<kanji>", "<category>", "<particle>"]

'''


var_aGreetings ={
    "Good morning.":"おはよう。",
    "Good morning. (polite)":"おはようございます。",
    "Good afternoon.":"こんにちは。",
    "Good evening.":"こんばんは。",
    "Good-bye.":"さようなら。",
    "Good night.":"おやすみ（なさい）。",
    "Thank you.":"ありがとう。",
    "Thank you. (polite)":"ありがとうございます。",
    "Excuse me.; I'm sorry.":"すみません。",
    "No.; Not at all.":"いいえ。",
    "I'll go and come back.":"行ってきます。",
    "Please go and come back.":"いってらっしゃい。",
    "I'm home.":"ただいま。",
    "Welcome home.":"おかえり（なさい）。",
    "Thank you for the meal. (before eating)":"いただきます。",
    "Thank you for the meal. (after eating)":"ごちそうさま（でした）。",
    "How do you do?":"はじめまして。",
    "Nice to meet you.":"よろしくおねがいします。",
    }

var_aLesson_1 ={
    "um..." : ["あの", "", "Gen.", "-"],
    "now" : ["いま", "今", "Gen.", "-"],
    "English (language)" : ["えいご", "英語", "Gen.", "-"],
    "yes" : ["はい／ええ", "", "Gen.", "-"],
    "student" : ["がくせい", "学生", "Gen.", "-"],
    "language" : ["〜ご", "〜語", "Gen.", "-"],
    "high school" : ["こうこう", "高校", "Gen.", "-"],
    "P.M." : ["ごご", "午後", "Gen.", "-"],
    "A.M." : ["ごぜん", "午前", "Gen.", "-"],
    "...years old" : ["〜さい", "〜歳", "Gen.", "-"],
    "Mr./Ms...." : ["〜さん", "", "Gen.", "-"],
    "o'clock" : ["〜じ", "〜時", "Gen.", "-"],
    "people" : ["〜じん", "〜人", "Gen.", "-"],
    "teacher; Professor ..." : ["せんせい", "先生", "Gen.", "-"],
    "major" : ["せんもん/せんこう", "専門", "Gen.", "-"],
    "That's right." : ["そうです", "", "Gen.", "-"],
    "I see; Is that so?" : ["そうですか", "", "Gen.", "-"],
    "college; university" : ["だいがく", "大学", "Gen.", "-"],
    "telephone" : ["でんわ", "電話", "Gen.", "-"],
    "friend" : ["ともだち", "友達", "Gen.", "-"],
    "name" : ["なまえ", "名前", "Gen.", "-"],
    "what" : ["なん／なに", "何", "Gen.", "-"],
    "Japan" : ["にほん", "日本", "Gen.", "-"],
    "...year student" : ["〜ねんせい", "〜年生", "Gen.", "-"],
    "half" : ["はん", "半", "Gen.", "-"],
    "number" : ["ばんごう", "番号", "Gen.", "-"],
    "international student" : ["りゅうがくせい", "留学生", "Gen.", "-"],
    "I" : ["わたし", "私", "Gen.", "-"],
    "U.S.A." : ["アメリカ", "", "Gen.", "-"],
    "Britain" : ["イギリス", "", "Gen.", "-"],
    "Australia" : ["オーストラリア", "", "Gen.", "-"],
    "Korea" : ["かんこく", "韓国", "Gen.", "-"],
    "Sweden" : ["スウェーデン", "", "Gen.", "-"],
    "China" : ["ちゅうごく", "中国", "Gen.", "-"],
    "science" : ["かがく", "科学", "Gen.", "-"],
    "Asian studies" : ["アジアけんきゅう", "アジア研究", "Gen.", "-"],
    "economics" : ["けいざい", "経済", "Gen.", "-"],
    "international relations" : ["こくさいかんけい", "国際関係", "Gen.", "-"],
    "computer" : ["コンピューター", "", "Gen.", "-"],
    "anthropology" : ["じんるいがく", "人類学", "Gen.", "-"],
    "politics" : ["せいじ", "政治", "Gen.", "-"],
    "business" : ["ビジネス", "", "Gen.", "-"],
    "literature" : ["ぶんがく", "文学", "Gen.", "-"],
    "history" : ["れきし", "歴史", "Gen.", "-"],
    "job; work; occupation" : ["しごと", "仕事", "Gen.", "-"],
    "doctor" : ["いしゃ", "医者", "Gen.", "-"],
    "office worker" : ["かいしゃいん", "会社員", "Gen.", "-"],
    "high school student" : ["こうこうせい", "高校生", "Gen.", "-"],
    "housewife" : ["しゅふ", "主婦", "Gen.", "-"],
    "graduate student" : ["だいがくいんせい", "大学院生", "Gen.", "-"],
    "college student" : ["だいがくせい", "大学生", "Gen.", "-"],
    "lawyer" : ["べんごし", "弁護士", "Gen.", "-"],
    "mother" : ["おかあさん", "お母さん", "Gen.", "-"],
    "father" : ["おとうさん", "お父さん", "Gen.", "-"],
    "older sister" : ["おねえさん", "お姉さん", "Gen.", "-"],
    "older brother" : ["おにいさん", "お兄さん", "Gen.", "-"],
    "younger sister" : ["いもうと", "妹", "Gen.", "-"],
    "younger brother" : ["おとうと", "弟", "Gen.", "-"],
    }


var_aLesson_2 ={
    "this one" : ["これ", "", "Gen.", "-"],
    "that one" : ["それ", "", "Gen.", "-"],
    "that one (over there)" : ["あれ", "", "Gen.", "-"],
    "which one" : ["どれ", "", "Gen.", "-"],
    "this ..." : ["この", "", "Gen.", "-"],
    "that ..." : ["その", "", "Gen.", "-"],
    "that ... (over there)" : ["あの", "", "Gen.", "-"],
    "which ..." : ["どの", "", "Gen.", "-"],
    "over there" : ["あそこ", "", "Gen.", "-"],
    "there" : ["そこ", "", "Gen.", "-"],
    "here" : ["ここ", "", "Gen.", "-"],
    "where" : ["どこ", "", "Gen.", "-"],
    "who" : ["だれ", "", "Gen.", "-"],
    "delicious" : ["おいしい", "", "i - adj", "-"],
    "fish" : ["さかな", "魚", "Gen.", "-"],
    "pork cutlet" : ["とんかつ", "", "Gen.", "-"],
    "meat" : ["にく", "肉", "Gen.", "-"],
    "menu" : ["メニュー", "", "Gen.", "-"],
    "vegetable" : ["やさい", "野菜", "Gen.", "-"],
    "pencil" : ["えんぴつ", "鉛筆", "Gen.", "-"],
    "umbrella" : ["かさ", "傘", "Gen.", "-"],
    "bag" : ["かばん", "", "Gen.", "-"],
    "shoes" : ["くつ", "靴", "Gen.", "-"],
    "wallet" : ["さいふ", "財布", "Gen.", "-"],
    "jeans" : ["ジーンズ", "", "Gen.", "-"],
    "dictionary" : ["じしょ", "辞書", "Gen.", "-"],
    "bicycle" : ["じてんしゃ", "自転車", "Gen.", "-"],
    "newspaper" : ["しんぶん", "新聞", "Gen.", "-"],
    "tape" : ["テープ", "", "Gen.", "-"],
    "T-shirt" : ["Tシャツ", "", "Gen.", "-"],
    "watch; clock" : ["とけい", "時計", "Gen.", "-"],
    "sweat shirt" : ["トレーナー", "", "Gen.", "-"],
    "notebook" : ["ノート", "", "Gen.", "-"],
    "pen" : ["ペン", "", "Gen.", "-"],
    "hat; cap" : ["ぼうし", "帽子", "Gen.", "-"],
    "book" : ["ほん", "本", "Gen.", "-"],
    "restroom" : ["おてあらい", "お手洗い", "Gen.", "-"],
    "cafe" : ["きっさてん", "喫茶店", "Gen.", "-"],
    "bank" : ["ぎんこう", "銀行", "Gen.", "-"],
    "library" : ["としょかん", "図書館", "Gen.", "-"],
    "post office" : ["ゆうびんきょく", "郵便局", "Gen.", "-"],
    "how much" : ["いくら", "", "Gen.", "-"],
    "...yen" : ["〜えん", "〜円", "Gen.", "-"],
    "expensive" : ["たかい", "高い", "i - adj", "-"],
    "Welcome (to our store)" : ["いらっしゃいませ", "", "Gen.", "-"],
    "..., please." : ["（〜を）おねがいします", "", "Gen.", "-"],
    "Please give me..." : ["（〜を）ください", "", "Gen.", "-"],
    "then...; if that is the case,..." : ["じゃあ", "", "Gen.", "-"],
    "Here it is." : ["（〜を）どうぞ", "", "Gen.", "-"],
    "Thank you." : ["どうも", "", "Gen.", "-"],
    "chair" : ["いす", "", "Gen.", "-"],
    "curtain" : ["カーテン", "", "Gen.", "-"],
    "eraser" : ["けしゴム", "消しゴム", "Gen.", "-"],
    "blackboard" : ["こくばん", "黒板", "Gen.", "-"],
    "door" : ["ドア", "", "Gen.", "-"],
    "Do you understand?" : ["わかりましたか。", "", "Phrase", "-"],
    "I understand./I understood." : ["わかりました。", "", "Phrase", "-"],
    "I don't understand./I don't know." : ["わかりません。", "", "Phrase", "-"],
    "Please say it slowly." : ["ゆっくりいってください。", "", "Phrase", "-"],
    "Please say it again." : ["もういちどいってください。", "", "Phrase", "-"],
    "Please wait." : ["ちょっとまってください。", "", "Phrase", "-"],
    "Please listen./Please ask." : ["きいてください。", "", "Phrase", "-"],
    "Please look at page 10." : ["10ページをみてください", "", "Phrase", "-"],
    }


var_aLesson_3 ={
    "movie" : ["えいが", "映画", "Gen.", "-"],
    "music" : ["おんがく", "音楽", "Gen.", "-"],
    "magazine" : ["ざっし", "雑誌", "Gen.", "-"],
    "sports" : ["スポーツ", "", "Gen.", "-"],
    "date (romantic, not calendar)" : ["デート", "", "Gen.", "-"],
    "tennis" : ["テニス", "", "Gen.", "-"],
    "TV" : ["テレビ", "", "Gen.", "-"],
    "video tape; VCR" : ["ビデオ", "", "Gen.", "-"],
    "ice cream" : ["アイスクリーム", "", "Gen.", "-"],
    "breakfast" : ["あさごはん", "朝御飯", "Gen.", "-"],
    "sake; alcohol" : ["おさけ", "お酒", "Gen.", "-"],
    "green tea" : ["おちゃ", "お茶", "Gen.", "-"],
    "coffee" : ["コーヒー", "", "Gen.", "-"],
    "dinner" : ["ばんごはん", "晩御飯", "Gen.", "-"],
    "hamburger" : ["ハンバーガー", "", "Gen.", "-"],
    "lunch" : ["ひるごはん", "昼御飯", "Gen.", "-"],
    "water" : ["みず", "水", "Gen.", "-"],
    "home; house" : ["いえ", "家", "Gen.", "-"],
    "home; house; my place" : ["うち", "家（ぼくの）", "Gen.", "-"],
    "school" : ["がっこう", "学校", "Gen.", "-"],
    "morning" : ["あさ", "朝", "Gen.", "-"],
    "tomorrow" : ["あした", "", "Gen.", "-"],
    "when" : ["いつ", "", "Gen.", "-"],
    "today" : ["きょう", "今日", "Gen.", "-"],
    "at about" : ["〜ごろ", "", "Gen.", "-"],
    "tonight" : ["こんばん", "今晩", "Gen.", "-"],
    "weekend" : ["しゅうまつ", "週末", "Gen.", "-"],
    "Saturday" : ["どようび", "土曜日", "Gen.", "-"],
    "Sunday" : ["にちようび", "日曜日", "Gen.", "-"],
    "every day" : ["まいにち", "毎日", "Gen.", "-"],
    "every night" : ["まいばん", "毎晩", "Gen.", "-"],
    "to go" : ["いく", "行く", "u - verb", "に／へ"],
    "to go back; to return" : ["かえる", "帰る", "u - verb", "に／へ"],
    "to listen; to hear; to ask" : ["きく", "聞く", "u - verb", "を"],
    "to drink" : ["のむ", "飲む", "u - verb", "を"],
    "to speak; to talk" : ["はなす", "話す", "u - verb", "を／で"],
    "to read" : ["よむ", "読む", "u - verb", "を"],
    "to get up" : ["おきる", "起きる", "ru - verb", "-"],
    "to eat" : ["たべる", "食べる", "ru - verb", "を"],
    "to sleep; to go to sleep" : ["ねる", "寝る", "ru - verb", "-"],
    "to see; to look at; to watch" : ["みる", "見る", "ru - verb", "を"],
    "to come" : ["くる", "来る", "irr - verb", "に／へ"],
    "to do; to decide on (an item); to wear small items (necktie, watch, etc.)" : ["する", "", "irr - verb", "を"],
    "to study" : ["べんきょうする", "勉強する", "irr - verb", "を"],
    "good" : ["いい", "", "i - adj", "-"],
    "early, fast" : ["はやい", "早い", "i - adj", "-"],
    "not much" : ["あまり+ negative", "", "adverb", "-"],
    "not at all" : ["ぜんぜん+ negative", "全然 ", "adverb", "-"],
    "usually" : ["たいてい", "大抵", "adverb", "-"],
    "a little" : ["ちょっと", "", "adverb", "-"],
    "sometimes" : ["ときどき", "時々", "adverb", "-"],
    "often; much; well" : ["よく", "", "adverb", "-"],
    "That's right.; Let me see." : ["そうですね", "", "Phrase", "-"],
    "but" : ["でも", "", "Phrase", "-"],
    "How about...?; How is...?" : ["どうですか", "", "Phrase", "-"],

    }


var_aLesson_4 ={
    "part-time job" : ["アルバイト", "", "Gen.", "-"],
    "shopping" : ["かいもの", "買い物", "Gen.", "-"],
    "class" : ["クラス", "", "Gen.", "-"],
    "you" : ["あなた", "", "Gen.", "-"],
    "dog" : ["いぬ", "犬", "Gen.", "-"],
    "souvenir" : ["おみやげ", "お土産", "Gen.", "-"],
    "child" : ["こども", "子供", "Gen.", "-"],
    "rice; meal" : ["ごはん", "御飯", "Gen.", "-"],
    "picture; photograph" : ["しゃしん", "写真", "Gen.", "-"],
    "desk" : ["つくえ", "机", "Gen.", "-"],
    "letter" : ["てがみ", "手紙", "Gen.", "-"],
    "cat" : ["ねこ", "猫", "Gen.", "-"],
    "bread" : ["パン", "", "Gen.", "-"],
    "person" : ["ひと", "人", "Gen.", "-"],
    "e-mail" : ["メール", "", "Gen.", "-"],
    "temple" : ["おてら", "お寺", "Gen.", "-"],
    "park" : ["こうえん", "公園", "Gen.", "-"],
    "supermarket" : ["スーパー", "", "Gen.", "-"],
    "department store" : ["デパート", "", "Gen.", "-"],
    "bus stop" : ["バスてい", "バス停", "Gen.", "-"],
    "hospital" : ["びょういん", "病院", "Gen.", "-"],
    "hotel" : ["ホテル", "", "Gen.", "-"],
    "bookstore" : ["ほんや", "本屋", "Gen.", "-"],
    "town; city" : ["まち", "町", "Gen.", "-"],
    "restaurant" : ["レストラン", "", "Gen.", "-"],
    "yesterday" : ["きのう", "昨日", "Gen.", "-"],
    "hours" : ["〜じかん", "〜時間", "Gen.", "-"],
    "one hour" : ["いちじかん", "一時間", "Gen.", "-"],
    "last week" : ["せんしゅう", "先週", "Gen.", "-"],
    "when...; at the time of..." : ["とき", "時", "Gen.", "-"],
    "Monday" : ["げつようび", "月曜日", "Gen.", "-"],
    "Tuesday" : ["かようび", "火曜日", "Gen.", "-"],
    "Wednesday" : ["すいようび", "水曜日", "Gen.", "-"],
    "Thursday" : ["もくようび", "木曜日", "Gen.", "-"],
    "Friday" : ["きんようび", "金曜日", "Gen.", "-"],
    "to meet; to see (a person)" : ["あう", "会う", "u - verb", "-"],
    "there is ..." : ["ある", "", "u - verb", "-"],
    "to buy" : ["かう", "買う", "u - verb", "-"],
    "to write" : ["かく", "書く", "u - verb", "-"],
    "to take (pictures)" : ["とる", "撮る", "u - verb", "-"],
    "to wait" : ["まつ", "待つ", "u - verb", "-"],
    "to understand" : ["わかる", "", "u - verb", "-"],
    "(a person) is in ...; stays at …," : ["いる", "", "ru - verb", "-"],
    "about (approximate measurement)" : ["〜ぐらい", "", "Gen.", "-"],
    "I'm sorry." : ["ごめんなさい", "", "Gen.", "-"],
    "so; therefore" : ["だから", "", "Gen.", "-"],
    "many; a lot" : ["たくさん", "", "Gen.", "-"],
    "together with (a person)" : ["〜と", "", "Gen.", "-"],
    "why" : ["どうして", "", "Gen.", "-"],
    "alone" : ["ひとりで", "一人で", "Gen.", "-"],
    "Hello? (used on the phone)" : ["もしもし", "", "Gen.", "-"],
    "right" : ["みぎ", "右", "Location", "の"],
    "left" : ["ひだり", "左", "Location", "の"],
    "front; before…" : ["まえ", "前", "Location", "の"],
    "back" : ["うしろ", "後ろ", "Location", "の"],
    "inside" : ["なか", "中", "Location", "の"],
    "on" : ["うえ", "上", "Location", "の"],
    "under" : ["した", "下", "Location", "の"],
    "next" : ["となり", "隣", "Location", "の"],
    "between" : ["あいだ", "間", "Location", "AとBの"],

    }


var_aLesson_5 ={
    "sea" : ["うみ", "海", "Gen.", "-"],
    "postal stamps" : ["きって", "切手", "Gen.", "-"],
    "ticket" : ["きっぷ", "切符", "Gen.", "-"],
    "surfing" : ["サーフィン", "", "Gen.", "-"],
    "homework" : ["しゅくだい", "宿題", "Gen.", "-"],
    "food" : ["たべもの", "食べ物", "Gen.", "-"],
    "birthday" : ["たんじょうび", "誕生日", "Gen.", "-"],
    "test" : ["テスト", "", "Gen.", "-"],
    "weather" : ["てんき", "天気", "Gen.", "-"],
    "drink" : ["のみもの", "飲み物", "Gen.", "-"],
    "postcard" : ["はがき", "葉書", "Gen.", "-"],
    "bus" : ["バス", "", "Gen.", "-"],
    "airplane" : ["ひこうき", "飛行機", "Gen.", "-"],
    "room" : ["へや", "部屋", "Gen.", "-"],
    "I (used by men)" : ["ぼく", "僕", "Gen.", "-"],
    "holiday; day off; absence" : ["やすみ", "休み", "Gen.", "-"],
    "travel" : ["りょこう", "旅行", "Gen.", "-"],
    "new" : ["あたらしい", "新しい", "i - adj", "-"],
    "hot (weather)" : ["あつい", "暑い", "i - adj", "-"],
    "hot (thing)" : ["あつい", "熱い", "i - adj", "-"],
    "busy (people/days)" : ["いそがしい", "忙しい", "i - adj", "-"],
    "large" : ["おおきい", "大きい", "i - adj", "-"],
    "interesting" : ["おもしろい", "面白い", "i - adj", "-"],
    "great-looking" : ["かっこいい", "", "i - adj", "-"],
    "frightening" : ["こわい", "怖い", "i - adj", "-"],
    "cold (weather-not used for objects)" : ["さむい", "寒い", "i - adj", "-"],
    "fun" : ["たのしい", "楽しい", "i - adj", "-"],
    "small" : ["ちいさい", "小さい", "i - adj", "-"],
    "boring" : ["つまらない", "", "i - adj", "-"],
    "old (thing - not used for people)" : ["ふるい", "古い", "i - adj", "-"],
    "difficult" : ["むずかしい", "難しい", "i - adj", "-"],
    "easy (problem); kind (person)" : ["やさしい", "", "i - adj", "-"],
    "inexpensive; cheap (thing)" : ["やすい", "安い", "i - adj", "-"],
    "disgusted with; to dislike" : ["きらい（な）", "嫌い", "na - adj", "が"],
    "beautiful; clean" : ["きれい（な）", "", "na - adj", "-"],
    "healthy; energetic" : ["げんき（な）", "元気", "na - adj", "-"],
    "quiet" : ["しずか（な）", "静か", "na - adj", "-"],
    "fond of; to like" : ["すき（な）", "好き", "na - adj", "が"],
    "to hate" : ["だいきらい（な）", "大嫌い", "na - adj", "が"],
    "very fond of; to love" : ["だいすき（な）", "大好き", "na - adj", "が"],
    "lively" : ["にぎやか（な）", "", "na - adj", "-"],
    "handsome" : ["ハンサム（な）", "", "na - adj", "-"],
    "not busy; to have a lot of free time" : ["ひま（な）", "暇", "na - adj", "-"],
    "to swim" : ["およぐ", "泳ぐ", "u - verb", "-"],
    "to ride; to board" : ["のる", "乗る", "u - verb", "に"],
    "to do; to perform; to give (to pets, plants, younger siblings, etc.)" : ["やる", "", "u - verb", "を"],
    "to go out" : ["でかける", "出かける", "ru - verb", "-"],
    "together" : ["いっしょに", "一緒に", "Gen.", "-"],
    "extremely" : ["すごく", "", "adverb", "-"],
    "and then" : ["それから", "", "Gen.", "-"],
    "It's okay.; Not to worry.; Everything is under control." : ["だいじょうぶ", "大丈夫", "Phrase", "-"],
    "very" : ["とても", "", "Gen.", "-"],
    "what kind of..." : ["どんな", "", "Gen.", "-"],
    "[counter for flat objects]" : ["〜まい", "〜枚", "Gen.", "-"],
    "to (a place); as far as (a place); till (a time)" : ["〜まで", "", "Gen.", "-"],
    "registered mail" : ["かきとめ", "書留", "Gen.", "-"],
    "airmail" : ["こうくうびん", "航空便", "Gen.", "-"],
    "parcel" : ["こづつみ", "小包", "Gen.", "-"],
    "special delivery" : ["そくたつ", "速達", "Gen.", "-"],
    "surface mail" : ["ふなびん", "船便", "Gen.", "-"],
    "insurance" : ["ほけん", "保険", "Gen.", "-"],
    "counter; ticket window" : ["まどぐち", "窓口", "Gen.", "-"],

    }


var_aLesson_6 ={
    "money" : ["おかね", "お金", "Gen.", "-"],
    "grandmother; old woman" : ["おばあさん", "", "Gen.", "-"],
    "bath" : ["おふろ", "お風呂", "Gen.", "-"],
    "kanji; Chinese character" : ["かんじ", "漢字", "Gen.", "-"],
    "textbook" : ["きょうかしょ", "教科書", "Gen.", "-"],
    "this week" : ["こんしゅう", "今週", "Gen.", "-"],
    "CD" : ["CD（シーディー）", "", "Gen.", "-"],
    "Municipal Hospital" : ["しみんびょういん", "市民病院", "Gen.", "-"],
    "shower" : ["シャワー", "", "Gen.", "-"],
    "next" : ["つぎ", "次", "Gen.", "-"],
    "video game" : ["テレビゲーム", "", "Gen.", "-"],
    "electricity" : ["でんき", "電気", "Gen.", "-"],
    "train" : ["でんしゃ", "電車", "Gen.", "-"],
    "baggage" : ["にもつ", "荷物", "Gen.", "-"],
    "personal computer" : ["パソコン", "", "Gen.", "-"],
    "page" : ["ページ", "", "Gen.", "-"],
    "window" : ["まど", "窓", "Gen.", "-"],
    "night" : ["よる", "夜", "Gen.", "-"],
    "next week" : ["らいしゅう", "来週", "Gen.", "-"],
    "next year" : ["らいねん", "来年", "Gen.", "-"],
    "tough (situation)" : ["たいへん（な）", "大変", "na - adj", "-"],
    "to play; to spend time pleasantly" : ["あそぶ", "遊ぶ", "u - verb", "-"],
    "to hurry" : ["いそぐ", "急ぐ", "u - verb", "-"],
    "to take a bath" : ["おふろにはいる", "お風呂に入る", "u - verb", "-"],
    "to return ( a thing)" : ["かえす", "返す", "u - verb", "PにTを"],
    "to turn off; to erase" : ["けす", "消す", "u - verb", "を"],
    "to die" : ["しぬ", "死ぬ", "u - verb", "-"],
    "to sit down" : ["すわる", "座る", "u - verb", "に"],
    "to stand up" : ["たつ", "立つ", "u - verb", "-"],
    "to smoke" : ["たばこをすう", "たばこを吸う", "u - verb", "-"],
    "to use" : ["つかう", "使う", "u - verb", "を"],
    "to help" : ["てつだう", "手伝う", "u - verb", "を"],
    "to enter" : ["はいる", "入る", "u - verb", "に"],
    "to carry; to hold" : ["もつ", "持つ", "u - verb", "を"],
    "to be absent (from...); to rest" : ["やすむ", "休む", "u - verb", "を"],
    "to open (something)" : ["あける", "開ける", "ru - verb", "を"],
    "to teach; to instruct" : ["おしえる", "教える", "ru - verb", "PにTを"],
    "to get off" : ["おりる", "降りる", "ru - verb", "を"],
    "to borrow" : ["かりる", "借りる", "ru - verb", "PにTを"],
    "to close (something)" : ["しめる", "閉める", "ru - verb", "を"],
    "to take a shower" : ["シャワーをあびる", "シャワーを浴びて", "ru - verb", "-"],
    "to turn on" : ["つける", "", "ru - verb", "を"],
    "to make a phone call" : ["でんわをかける", "電話をかける", "ru - verb", "PにTを"],
    "to forget; to leave behind" : ["わすれる", "忘れる", "ru - verb", "を"],
    "to bring (a person)" : ["つれてくる", "連れてくる", "irr - verb", "を"],
    "to bring (a thing)" : ["もってくる", "持ってくる", "irr - verb", "を"],
    "later on" : ["あとで", "後で", "Gen.", "-"],
    "(do something) late" : ["おそく", "遅く", "adverb", "-"],
    "because ..." : ["〜から", "", "Gen.", "-"],
    "That would be fine.; That wouldn't be necessary." : ["けっこうです", "結構です", "Phrase", "-"],
    "right away" : ["すぐ", "", "adverb", "-"],
    "Really?" : ["ほんとうですか", "本当ですか", "Gen.", "-"],
    "slowly; leisurely; unhurriedly" : ["ゆっくり", "", "adverb", "-"],
    "corner" : ["かど", "角", "Gen.", "-"],
    "north" : ["きた", "北", "Gen.", "-"],
    "traffic light" : ["しんごう", "信号", "Gen.", "-"],
    "west" : ["にし", "西", "Gen.", "-"],
    "east" : ["ひがし", "東", "Gen.", "-"],
    "left side" : ["ひだりがわ", "左側", "Gen.", "-"],
    "first" : ["ひとつめ", "一つ目", "Gen.", "-"],
    "second" : ["ふたつめ", "二つ目", "Gen.", "-"],
    "to turn (right/left)" : ["まがる", "曲がる", "u - verb", "-"],
    "right side" : ["みぎがわ", "右側", "Gen.", "-"],
    "south" : ["みなみ", "南", "Gen.", "-"],
    "to cross" : ["わたる", "渡る", "u - verb", "-"],

    }


var_aLesson_7 ={
    "(my) older sister" : ["あね", "姉", "Gen.", "-"],
    "apartment" : ["アパート", "", "Gen.", "-"],
    "song" : ["うた", "歌", "Gen.", "-"],
    "man" : ["おとこのひと", "男の人", "Gen.", "-"],
    "woman" : ["おんなのひと", "女の人", "Gen.", "-"],
    "company" : ["かいしゃ", "会社", "Gen.", "-"],
    "family" : ["かぞく", "家族", "Gen.", "-"],
    "hair" : ["かみ", "髪", "Gen.", "-"],
    "brothers and sisters" : ["きょうだい", "兄弟", "Gen.", "-"],
    "country; place of origin" : ["くに", "国", "Gen.", "-"],
    "car" : ["くるま", "車", "Gen.", "-"],
    "game" : ["ゲーム", "", "Gen.", "-"],
    "convenience store" : ["コンビニ", "", "Gen.", "-"],
    "club activity" : ["サークル", "", "Gen.", "-"],
    "cafeteria; dining commons" : ["しょくどう", "食堂", "Gen.", "-"],
    "(my) father" : ["ちち", "父", "Gen.", "-"],
    "DVD" : ["DVD（ディーヴェーディー）", "", "Gen.", "-"],
    "(my) mother" : ["はは", "母", "Gen.", "-"],
    "eye" : ["め", "目", "Gen.", "-"],
    "glasses" : ["めがね", "眼鏡", "Gen.", "-"],
    "bright; smart; clever" : ["あたまがいい", "頭がいい", "i - adj", "-"],
    "cute" : ["かわいい", "", "i - adj", "-"],
    "tall (stature)" : ["せがたかい", "背が高い", "i - adj", "-"],
    "short (stature)" : ["せがひくい", "背が低い", "i - adj", "-"],
    "long" : ["ながい", "長い", "i - adj", "-"],
    "short (length)" : ["みじかい", "短い", "i - adj", "-"],
    "kind" : ["しんせつ", "親切", "na - adj", "-"],
    "convenient" : ["べんり", "便利", "na - adj", "-"],
    "to sing" : ["うたう", "歌う", "u - verb", "を"],
    "to put on (a hat)" : ["かぶる", "", "u - verb", "を"],
    "to get to know" : ["しる", "知る", "u - verb", "を"],
    "I know" : ["しっています", "知っています", "u - verb", "-"],
    "I do not know" : ["しりません", "知りません", "u - verb", "-"],
    "to live" : ["すむ", "住む", "u - verb", "～にすんでいます"],
    "to put on (items below your waist)" : ["はく", "", "u - verb", "を"],
    "to gain weight" : ["ふとる", "太る", "u - verb", "-"],
    "to be on the heavy side" : ["ふとっています", "太っています", "u - verb", "-"],
    "to put on (glasses)" : ["（めがね）をかける", "", "ru - verb", "-"],
    "to put on (clothes above your waist)" : ["きる", "着る", "ru - verb", "-"],
    "to work for" : ["つとめる", "務める", "ru - verb", "～につとめています"],
    "to lose weight" : ["やせる", "", "ru - verb", "-"],
    "to be thin" : ["やせています", "", "ru - verb", "-"],
    "to get married" : ["けっこんする", "結婚する", "ru - verb", "と"],
    "...but" : ["～が", "", "Gen.", "-"],
    "not…anything" : ["なにも　+ negative", "何も", "Gen.", "-"],
    "[counter for people]" : ["～にん", "～人", "Gen.", "-"],
    "one person" : ["ひとり", "一人", "Gen.", "-"],
    "two people" : ["ふたり", "二人", "Gen.", "-"],
    "nothing in particular" : ["べつに + negative", "別に", "Gen.", "-"],
    "of course" : ["もちろん", "", "Gen.", "-"],
    "if you like" : ["よかったら", "", "Gen.", "-"],
    "head" : ["あたま", "頭", "Gen.", "-"],
    "(my) older brother" : ["あに", "兄", "Gen.", "-"],
    "grandfather; old man" : ["おじいさん", "", "Gen.", "-"],
    "buttocks" : ["おしり", "", "Gen.", "-"],
    "shoulder" : ["かた", "肩", "Gen.", "-"],
    "mouth" : ["くち", "口", "Gen.", "-"],
    "neck" : ["くび", "首", "Gen.", "-"],
    "buttocks" : ["しり", "", "Gen.", "-"],
    "back" : ["せなか", "背中", "Gen.", "-"],
    "(my) grandfather" : ["そふ", "祖父", "Gen.", "-"],
    "(my) grandmother" : ["そぼ", "祖母", "Gen.", "-"],
    "hand" : ["て", "手", "Gen.", "-"],
    "nose" : ["はな", "鼻", "Gen.", "-"],
    "ear" : ["みみ", "耳", "Gen.", "-"],
    "breast" : ["むね", "胸", "Gen.", "-"],
    "finger" : ["ゆび", "指", "Gen.", "-"],

    }


var_aLesson_8 ={
    "the day after tomorrow" : ["あさって", "", "Gen.", "-"],
    "rain" : ["あめ", "雨", "Gen.", "-"],
    "camera" : ["カメラ", "", "Gen.", "-"],
    "karaoke" : ["カラオケ", "", "Gen.", "-"],
    "air" : ["くうき", "空気", "Gen.", "-"],
    "this morning" : ["けさ", "今朝", "Gen.", "-"],
    "this month" : ["こんげつ", "今月", "Gen.", "-"],
    "disco" : ["ディスコ", "", "Gen.", "-"],
    "weather forecast" : ["てんきよほう", "天気予報", "Gen.", "-"],
    "place" : ["ところ", "所", "Gen.", "-"],
    "tomato" : ["トマト", "", "Gen.", "-"],
    "summer" : ["なつ", "夏", "Gen.", "-"],
    "something" : ["なにか", "何か", "Gen.", "-"],
    "party" : ["パーティー", "", "Gen.", "-"],
    "barbecue" : ["バーベキュー", "", "Gen.", "-"],
    "chopsticks" : ["はし", "", "Gen.", "-"],
    "winter" : ["ふゆ", "冬", "Gen.", "-"],
    "homestay; living with a local family" : ["ホームステイ", "", "Gen.", "-"],
    "every week" : ["まいしゅう", "毎週", "Gen.", "-"],
    "next month" : ["らいげつ", "来月", "Gen.", "-"],
    "skillful; good at..." : ["じょうず", "上手", "na - adj", "が"],
    "clumsy; poor at..." : ["へた", "下手", "na - adj", "が"],
    "famous" : ["ゆうめい", "有名", "na - adj", "-"],
    "it rains" : ["あめがふる", "雨が降る", "u - verb", "-"],
    "to wash" : ["あらう", "洗う", "u - verb", "を"],
    "to say" : ["いう", "言う", "u - verb", "-"],
    "to need" : ["いる", "", "u - verb", "が"],
    "to be late (for ...)" : ["おそくなる", "遅くなる", "u - verb", "-"],
    "to think" : ["おもう", "思う", "u - verb", "-"],
    "to cut" : ["きる", "切る", "u - verb", "を"],
    "to make" : ["つくる", "作る", "u - verb", "を"],
    "to take (a thing)" : ["もっていく", "持っていく", "u - verb", "を"],
    "to stare (at ...)" : ["じろじろみる", "じろじろ見る", "ru - verb", "を"],
    "to throw away" : ["すてる", "捨てる", "ru - verb", "を"],
    "to begin" : ["はじめる", "始める", "ru - verb", "を"],
    "to drive" : ["うんてんする", "運転する", "irr - verb", "を"],
    "to do laundry" : ["せんたくする", "洗濯する", "irr - verb", "を"],
    "to clean" : ["そうじする", "掃除する", "irr - verb", "を"],
    "to cook" : ["りょうりする", "料理する", "irr - verb", "-"],
    "to call" : ["でんわする", "電話する", "irr - verb", "に"],
    "always" : ["いつも", "", "Gen.", "-"],
    "uh-uh; no" : ["ううん", "", "Gen.", "-"],
    "uh-huh; yes" : ["うん", "", "Gen.", "-"],
    "Cheers! (a toast)" : ["かんぱい", "乾杯", "Gen.", "-"],
    "That's too bad." : ["ざんねん（ですね）", "残念ですね", "Gen.", "-"],
    "all (of the people) together" : ["みんなで", "", "Gen.", "-"],
    "about…; concerning…" : ["～について", "", "Gen.", "-"],
    "not…yet" : ["まだ + negative", "", "Gen.", "-"],

    }


var_aLesson_9 ={
    "good child" : ["いいこ", "いい子", "Gen.", "-"],
    "color" : ["いろ", "色", "Gen.", "-"],
    "boxed lunch" : ["おべんとう", "お弁当", "Gen.", "-"],
    "Kabuki; traditional Japanese theatrical art" : ["かぶき", "", "Gen.", "-"],
    "guitar" : ["ギター", "", "Gen.", "-"],
    "medicine" : ["くすり", "薬", "Gen.", "-"],
    "to take medicine" : ["くすりをのむ", "薬を飲む", "Gen.", "-"],
    "concert" : ["コンサート", "", "Gen.", "-"],
    "near future" : ["こんど", "今度", "Gen.", "-"],
    "essay; composition" : ["さくぶん", "作文", "Gen.", "-"],
    "exam" : ["しけん", "試験", "Gen.", "-"],
    "ski" : ["スキー", "", "Gen.", "-"],
    "last month" : ["せんげつ", "先月", "Gen.", "-"],
    "word; vocabulary" : ["たんご", "単語", "Gen.", "-"],
    "piano" : ["ピアノ", "", "Gen.", "-"],
    "pizza" : ["ピザ", "", "Gen.", "-"],
    "illness; sickness" : ["びょうき", "病気", "Gen.", "-"],
    "blue" : ["あおい", "青い", "i - adj", "-"],
    "red" : ["あかい", "赤い", "i - adj", "-"],
    "black" : ["くろい", "黒い", "i - adj", "-"],
    "lonely" : ["さびしい", "寂しい", "i - adj", "-"],
    "white" : ["しろい", "白い", "i - adj", "-"],
    "young" : ["わかい", "若い", "i - adj", "-"],
    "mean-spirited" : ["いじわる", "意地悪", "na - adj", "-"],
    "to dance" : ["おどる", "踊る", "u - verb", "-"],
    "(something) ends" : ["おわる", "終わる", "u - verb", "を"],
    "to be popular" : ["にんきがある", "人気がある", "u - verb", "-"],
    "(something) begins" : ["はじまる", "始まる", "u - verb", "～が"],
    "to play (a string instrument or piano)" : ["ひく", "弾く", "u - verb", "を"],
    "to get (from somebody)" : ["もらう", "", "u - verb", "PにTを"],
    "to memorize" : ["おぼえる", "覚える", "ru - verb", "を"],
    "-1 to appear; to attend -2 to exit" : ["でる", "出る", "ru - verb", "に／を"],
    "to do physical exercises" : ["うんどうする", "運動する", "irr - verb", "-"],
    "to take a walk" : ["さんぽする", "散歩する", "irr - verb", "-"],
    "from…" : ["～から", "", "Gen.", "-"],
    "by all means" : ["ぜひ", "是非", "Gen.", "-"],
    "by the way" : ["ところで", "", "Gen.", "-"],
    "all" : ["みんな", "", "Gen.", "-"],
    "already" : ["もう", "", "Gen.", "-"],
    "to look pale" : ["かおがあおい", "顔が青い", "Phrase", "-"],
    "yellow" : ["きいろい", "黄色い", "i - adj", "-"],
    "gold" : ["きんいろ", "金色", "na - adj", "-"],
    "silver" : ["ぎんいろ", "銀色", "na - adj", "-"],
    "blonde hair" : ["きんぱつ", "金髪", "Gen.", "-"],
    "gray" : ["はいいろ／グレー", "グレー", "na - adj", "-"],
    "gold" : ["きんいろ／ゴールド", "ゴールド", "na - adj", "-"],
    "silver" : ["ぎんいろ／シルバー", "シルバー", "na - adj", "-"],
    "black and white" : ["しろくろ", "白黒", "Gen.              (no adj)", "-"],
    "brown" : ["ちゃいろい", "茶色い", "i - adj", "-"],
    "pink" : ["ピンク", "", "na - adj", "-"],
    "light blue" : ["みずいろ", "水色", "na - adj", "-"],
    "green" : ["みどり／グリーン", "緑", "na - adj", "-"],
    "purple" : ["むらさき", "紫", "na - adj", "-"],

    }


var_aaLesson_10 ={
    "fall" : ["あき", "秋", "Gen.", "-"],
    "station" : ["えき", "駅", "Gen.", "-"],
    "rich person" : ["おかねもち", "お金持ち", "Gen.", "-"],
    "face" : ["かお", "顔", "Gen.", "-"],
    "season" : ["きせつ", "季節", "Gen.", "-"],
    "milk" : ["ぎゅうにゅう", "牛乳", "Gen.", "-"],
    "credit card" : ["クレジットカード", "", "Gen.", "-"],
    "cake" : ["ケーキ", "", "Gen.", "-"],
    "this year" : ["ことし", "今年", "Gen.", "-"],
    "soccer" : ["サッカー", "", "Gen.", "-"],
    "shirt" : ["シャツ", "", "Gen.", "-"],
    "Shinkansen; Bullet Train" : ["しんかんせん", "新幹線", "Gen.", "-"],
    "sushi" : ["すし", "", "Gen.", "-"],
    "life; living" : ["せいかつ", "生活", "Gen.", "-"],
    "world" : ["せかい", "世界", "Gen.", "-"],
    "subway" : ["ちかてつ", "地下鉄", "Gen.", "-"],
    "gloves" : ["てぶくろ", "手袋", "Gen.", "-"],
    "tempura" : ["てんぷら", "天ぷら", "Gen.", "-"],
    "barber's" : ["とこや", "床屋", "Gen.", "-"],
    "spring" : ["はる", "春", "Gen.", "-"],
    "pants" : ["パンツ", "", "Gen.", "-"],
    "beauty parlor" : ["びよういん", "美容院", "Gen.", "-"],
    "flight" : ["びん", "便", "Gen.", "-"],
    "ship; boat" : ["ふね", "船", "Gen.", "-"],
    "baseball" : ["やきゅう", "野球", "Gen.", "-"],
    "celebrity" : ["ゆうめいじん", "有名人", "Gen.", "-"],
    "reservation" : ["よやく", "予約", "Gen.", "-"],
    "next semester" : ["らいがっき", "来学期", "Gen.", "-"],
    "apple" : ["りんご", "", "Gen.", "-"],
    "warm" : ["あたたかい", "暖かい", "i - adj", "-"],
    "slow; late" : ["おそい", "遅い", "i - adj", "-"],
    "cool (weather)" : ["すずしい", "涼しい", "i - adj", "-"],
    "cold (thing/people)" : ["つめたい", "冷たい", "i - adj", "-"],
    "sleepy" : ["ねむい", "眠い", "i - adj", "-"],
    "easy; simple" : ["かんたん", "簡単", "na - adj", "-"],
    "to take (amount of time / money)" : ["かかる", "", "u - verb", "No part."],
    "to stay (at a hotel, etc.)" : ["とまる", "泊まる", "u - verb", "-"],
    "to become" : ["なる", "", "u - verb", "-"],
    "to pay" : ["はらう", "払う", "u - verb", "-"],
    "to decide" : ["きめる", "決める", "ru - verb", "-"],
    "to travel" : ["りょこうする", "旅行する", "ru - verb", "-"],
    "to practice" : ["れんしゅうする", "練習する", "irr - verb", "-"],
    "on foot" : ["あるいて", "歩いて", "Gen.", "-"],
    "best" : ["いちばん", "一番", "Gen.", "-"],
    "or" : ["～か～", "", "Gen.", "-"],
    "for…months" : ["～かげつ", "～か月", "Gen.", "-"],
    "in…time;after…" : ["～ご", "～後", "Gen.", "-"],
    "these days" : ["このごろ", "", "Gen.", "-"],
    "for…weeks" : ["～しゅうかん", "～週間", "Gen.", "-"],
    "how; by what means" : ["どうやって", "", "Gen.", "-"],
    "which" : ["どちら／どちゃ", "どちら", "Gen.", "-"],
    "how much; how long" : ["どのぐらい", "", "Gen.", "-"],
    "(do something) early; fast" : ["はやく", "早く", "adverb", "-"],
    "bound for…" : ["～いき", "～行き", "Gen.", "-"],
    "Car No. 1" : ["いちごうしゃ", "一号車", "Gen.", "-"],
    "last car; tail end" : ["いちばんうしろ", "一番後ろ", "Gen.", "-"],
    "first car; front end" : ["いちばんまえ", "一番前", "Gen.", "-"],
    "entrance" : ["いりぐち", "入口", "Gen.", "-"],
    "round trip" : ["おうふく", "往復", "Gen.", "-"],
    "gate" : ["かいさつ", "改札", "Gen.", "-"],
    "coupons" : ["かいすうけん", "回数券", "Gen.", "-"],
    "stairs" : ["かいだん", "階段", "Gen.", "-"],
    "student discount" : ["がくわり", "学割", "Gen.", "-"],
    "one way" : ["かたみち", "片道", "Gen.", "-"],
    "ticket vending area" : ["きっぷうりば", "切符売り場", "Gen.", "-"],
    "express" : ["きゅうこう", "急行", "Gen.", "-"],
    "nonsmoking car" : ["きんえんしゃ", "禁煙車", "Gen.", "-"],
    "reserved seat" : ["していせき", "指定席", "Gen.", "-"],
    "departing second" : ["じはつ", "次発", "Gen.", "-"],
    "Gen. admission seat" : ["じゆうせき", "自由席", "Gen.", "-"],
    "last train" : ["しゅうでん", "終電", "Gen.", "-"],
    "(boarding) ticket" : ["じょうしゃけん", "乗車券", "Gen.", "-"],
    "departing first" : ["せんぱつ", "先発", "Gen.", "-"],
    "next (stop),…" : ["つぎは～", "次は～", "Gen.", "-"],
    "commuter's pass" : ["ていきけん", "定期券", "Gen.", "-"],
    "exit" : ["でぐち", "出口", "Gen.", "-"],
    "super express" : ["とっきゅう", "特急", "Gen.", "-"],
    "transfer" : ["のりかえ", "乗り換え", "Gen.", "-"],
    "kiosk; shop; stand" : ["ばいてん", "売店", "Gen.", "-"],
    "track number…" : ["～ばんせん", "～番線", "Gen.", "-"],
    "local (train)" : ["ふつう", "普通", "Gen.", "-"],
    "serving…areas" : ["～ほうめん", "～方面", "Gen.", "-"],
    "platform" : ["ホーム", "", "Gen.", "-"],

    }


var_aaLesson_11 ={
    "snack; sweets" : ["おかし", "お菓子", "Gen.", "-"],
    "New Year's" : ["おしょうがつ", "お正月", "Gen.", "-"],
    "boy" : ["おとこのこ", "男の子", "Gen.", "-"],
    "festival" : ["おまつり", "お祭り", "Gen.", "-"],
    "toy" : ["おもちゃ", "", "Gen.", "-"],
    "spa; hot spring" : ["おんせん", "温泉", "Gen.", "-"],
    "girl" : ["おんなのこ", "女の子", "Gen.", "-"],
    "foreign country" : ["がいこく", "外国", "Gen.", "-"],
    "singer" : ["かしゅ", "歌手", "Gen.", "-"],
    "river" : ["かわ", "川", "Gen.", "-"],
    "camp" : ["キャンプ", "", "Gen.", "-"],
    "this person (polite)" : ["こちら", "", "Gen.", "-"],
    "this semester" : ["こんがっき", "今学期", "Gen.", "-"],
    "president of a company" : ["しゃちょう", "社長", "Gen.", "-"],
    "class" : ["じゅぎょう", "授業", "Gen.", "-"],
    "future" : ["しょうらい", "将来", "Gen.", "-"],
    "shrine" : ["じんじゃ", "神社", "Gen.", "-"],
    "fishing" : ["つり", "", "Gen.", "-"],
    "drive" : ["ドライブ", "", "Gen.", "-"],
    "beer" : ["ビール", "", "Gen.", "-"],
    "art museum" : ["びじゅつかん", "美術館", "Gen.", "-"],
    "host family" : ["ホストファミリー", "", "Gen.", "-"],
    "lake" : ["みずうみ", "湖", "Gen.", "-"],
    "mountain" : ["やま", "山", "Gen.", "-"],
    "dream" : ["ゆめ", "夢", "Gen.", "-"],
    "roommate" : ["ルームメート", "", "Gen.", "-"],
    "to tell a lie" : ["うそをつく", "", "u - verb", "-"],
    "to become hungry" : ["おなかがすく", "", "u - verb", "-"],
    "to own (a pet)" : ["かう", "飼う", "u - verb", "を"],
    "to cut classes" : ["サボる", "", "u - verb", "を"],
    "to take (a class); to get (a grade)" : ["とる", "取る", "u - verb", "を"],
    "to learn" : ["ならう", "習う", "u - verb", "を"],
    "to climb" : ["のぼる", "登る", "u - verb", "に"],
    "to work" : ["はたらく", "働く", "u - verb", "-"],
    "to get tired" : ["つかれる", "疲れる", "ru - verb", "-"],
    "to quit" : ["やめる", "", "ru - verb", "を"],
    "to have a fight; to quarrel" : ["けんかする", "", "irr - verb", "-"],
    "to introduce" : ["しょうかいする", "紹介する", "irr - verb", "PにPを"],
    "to go on a diet" : ["ダイエットする", "", "irr - verb", "-"],
    "to be late (for an appointment)" : ["ちこくする", "遅刻する", "irr - verb", "に"],
    "to study abroad" : ["りゅうがくする", "留学する", "irr - verb", "Plに"],
    "after (an event); the rest" : ["あと", "後", "Gen.", "-"],
    "coming from" : ["しゅっしん", "出身", "Gen.", "-"],
    "and then" : ["そして", "", "Gen.", "-"],
    "it has been a long time" : ["ひさしぶり", "久しぶり", "Gen.", "-"],
    "just…;only…" : ["～だけ", "", "Gen.", "-"],
    "…points" : ["～てん", "～点", "Gen.", "-"],
    "okay; so-so" : ["まあまあ", "", "Gen.", "-"],
    "more" : ["もっと", "", "Gen.", "-"],
    "writer" : ["さっか", "作家", "Gen.", "-"],
    "journalist" : ["ジャーナリスト", "", "Gen.", "-"],
    "police officer" : ["けいさつかん", "警察官", "Gen.", "-"],
    "actor; actress" : ["はいゆう", "俳優", "Gen.", "-"],
    "astronaut" : ["うちゅうひこうし", "宇宙飛行士", "Gen.", "-"],
    "baseball player" : ["やきゅうせんしゅ", "野球選手", "Gen.", "-"],
    "president of a country" : ["だいとうりょう", "大統領", "Gen.", "-"],
    "actress" : ["じょゆう", "女優", "Gen.", "-"],
    "nurse" : ["かんごし", "看護師", "Gen.", "-"],
    "firefighter" : ["しょうぼうし", "消防士", "Gen.", "-"],
    "cartoonist" : ["まんがか", "漫画家", "Gen.", "-"],
    "bookish expression" : ["かたいいいかた", "かたい言い方", "Gen.", "-"],
    "parenthesis" : ["かっこ", "", "Gen.", "-"],
    "line number…" : ["～ぎょうめ", "～行目", "Gen.", "-"],
    "colloquial expression" : ["くだけたいいかた", "くだけた言い方", "Gen.", "-"],
    "answer" : ["こたえ", "答", "Gen.", "-"],
    "question" : ["しつもん", "質問", "Gen.", "-"],
    "deadline" : ["しめきり", "", "Gen.", "-"],
    "for example" : ["たとえば", "", "Gen.", "-"],
    "polite expression" : ["ていねいないいかた", "ていねいな言い方", "Gen.", "-"],
    "x (wrong)" : ["ばつ", "", "Gen.", "-"],
    "pronunciation" : ["はつおん", "発音", "Gen.", "-"],
    "number…" : ["～ばん", "～番", "Gen.", "-"],
    "standard Japanese" : ["ひょうじゅんご", "標準語", "Gen.", "-"],
    "two people each" : ["ふたりずつ", "二人ずつ", "Gen.", "-"],
    "grammar" : ["ぶんぽう", "文法", "Gen.", "-"],
    "page number…" : ["～ページ", "", "Gen.", "-"],
    "dialect" : ["ほうげん", "方言", "Gen.", "-"],
    "anything else" : ["ほかに", "", "Gen.", "-"],
    "O (correct)" : ["まる", "", "Gen.", "-"],
    "example" : ["れい", "例", "Gen.", "-"],
    "exercise (problem)" : ["れんしゅう", "練習", "Gen.", "-"],
    "meaning" : ["いみ", "意味", "Gen.", "-"],

    }


var_aaLesson_12 ={
    "leg; foot" : ["あし", "足", "Gen.", "-"],
    "meaning" : ["いみ", "意味", "Gen.", "-"],
    "stomach" : ["おなか", "", "Gen.", "-"],
    "cold" : ["かぜ", "風", "Gen.", "-"],
    "girlfriend" : ["かのじょ", "彼女", "Gen.", "-"],
    "boyfriend" : ["かれ", "彼", "Gen.", "-"],
    "temperature (weather)" : ["きおん", "気温", "Gen.", "-"],
    "cloudy weather" : ["くもり", "曇り", "Gen.", "-"],
    "match; game" : ["しあい", "試合", "Gen.", "-"],
    "juice" : ["ジュース", "", "Gen.", "-"],
    "cough" : ["せき", "咳", "Gen.", "-"],
    "throat" : ["のど", "", "Gen.", "-"],
    "tooth" : ["は", "歯", "Gen.", "-"],
    "flower" : ["はな", "花", "Gen.", "-"],
    "sunny weather" : ["はれ", "晴れ", "Gen.", "-"],
    "clothes" : ["ふく", "服", "Gen.", "-"],
    "hangover" : ["ふつかよい", "二日酔い", "Gen.", "-"],
    "present" : ["プレゼント", "", "Gen.", "-"],
    "homesickness" : ["ホームシック", "", "Gen.", "-"],
    "minus" : ["マイナス", "", "Gen.", "-"],
    "thing (concrete object)" : ["もの", "物", "Gen.", "-"],
    "snow" : ["ゆき", "雪", "Gen.", "-"],
    "business to take care of" : ["ようじ", "用事", "Gen.", "-"],
    "sweet" : ["あまい", "甘い", "i - adj", "-"],
    "hurt; painful" : ["いたい", "痛い", "i - adj", "-"],
    "there are many..." : ["おおい", "多い", "i - adj", "-"],
    "narrow; not spacious" : ["せまい", "狭い", "i - adj", "-"],
    "inconvenient; to have a scheduling conflict" : ["つごうがわるい", "都合が悪い", "i - adj", "-"],
    "bad" : ["わるい", "悪い", "i - adj", "-"],
    "nice" : ["すてき", "素敵", "na - adj", "-"],
    "to walk" : ["あるく", "歩く", "u - verb", "-"],
    "to catch a cold" : ["かぜをひく", "風邪をひく", "u - verb", "-"],
    "to be interested (in ...)" : ["きょうみがある", "興味がある", "u - verb", "に"],
    "to lose" : ["なくす", "", "u - verb", "を"],
    "to become thirsty" : ["のどがかわく", "のどが渇く", "u - verb", "-"],
    "to have a fever" : ["ねつがある", "熱がある", "u - verb", "-"],
    "to cough" : ["せきがでる", "せきが出る", "ru - verb", "-"],
    "to break up; to separate" : ["わかれる", "別れる", "ru - verb", "Pと"],
    "to get nervous" : ["きんちょうする", "緊張する", "irr - verb", "-"],
    "to worry" : ["しんぱいする", "心配する", "irr - verb", "-"],
    "Get well soon." : ["おだいじに", "お大事に", "Gen.", "-"],
    "don't look well" : ["げんきがない", "元気がない", "Gen.", "-"],
    "probably; maybe" : ["たぶん", "多分", "Gen.", "-"],
    "as much as possible" : ["できるだけ", "", "Gen.", "-"],
    "probably; …,right?" : ["～でしょう", "", "Gen.", "-"],
    "…degrees (temperature)" : ["～ど", "～度", "Gen.", "-"],
    "for two to three days" : ["にさんにち", "二三日", "Gen.", "-"],
    "because…" : ["～ので", "", "Gen.", "-"],
    "for the first time" : ["はじめて", "初めて", "Gen.", "-"],
    "very soon; in a few moments/days" : ["もうすぐ", "", "Gen.", "-"],
    "ophthalmologist" : ["がんか", "眼科", "Gen.", "-"],
    "injury" : ["けが", "", "Gen.", "-"],
    "surgeon" : ["げか", "外科", "Gen.", "-"],
    "antibiotic" : ["こうせいぶっしつ", "抗生物質", "Gen.", "-"],
    "obstetrician and gynecologist" : ["さんふじんか", "産婦人科", "Gen.", "-"],
    "dentist" : ["しか", "歯科", "Gen.", "-"],
    "otorhinolaryngologist; ENT doctor" : ["じびか", "耳鼻科", "Gen.", "-"],
    "operation" : ["しゅじゅつ", "手術", "Gen.", "-"],
    "orthopedic surgeon" : ["せいけいげか", "整形外科", "Gen.", "-"],
    "thermometer" : ["たいおんけい", "体温計", "Gen.", "-"],
    "injection" : ["ちゅうしゃ", "注射", "Gen.", "-"],
    "physician" : ["ないか", "内科", "Gen.", "-"],
    "dermatologist" : ["ひふか", "皮膚科", "Gen.", "-"],
    "X-ray" : ["レントゲン", "", "Gen.", "-"],

    }

var_aaLesson_13 = {
    "waiter" : ["ウェイター", "ウェイター", "Gen.", "-"],
    "someone's house" : ["おたく", "お宅", "Gen.", "-"],
    "adult" : ["おとな", "大人", "Gen.", "-"],
    "foreign language" : ["がいこくご", "外国語", "Gen.", "-"],
    "musical instrument" : ["がっき", "楽器", "Gen.", "-"],
    "karate" : ["からて", "空手", "Gen.", "-"],
    "curry" : ["カレー", "カレー", "Gen.", "-"],
    "kimono; Japanese traditional dress" : ["きもの", "着物", "Gen.", "-"],
    "advertisement" : ["こうこく", "広告", "Gen.", "-"],
    "tea (black tea)" : ["こうちゃ", "紅茶", "Gen.", "-"],
    "language" : ["ことば", "言葉", "Gen.", "-"],
    "golf" : ["ゴルフ", "ゴルフ", "Gen.", "-"],
    "sweater" : ["セーター", "セーター", "Gen.", "-"],
    "elephant" : ["ぞう", "象", "Gen.", "-"],
    "violin" : ["バイオリン", "バイオリン", "Gen.", "-"],
    "motorbike" : ["バイク", "バイク", "Gen.", "-"],
    "(consumer) prices" : ["ぶっか", "物価", "Gen.", "-"],
    "grammar" : ["ぶんぽう", "文法", "Gen.", "-"],
    "recruitment" : ["ぼしゅう", "募集", "Gen.", "-"],
    "shop; store" : ["みせ", "店", "Gen.", "-"],
    "yakuza; gangster" : ["やくざ", "やくざ", "Gen.", "-"],
    "promise; appointment" : ["やくそく", "約束", "Gen.", "-"],
    "(term) paper" : ["レポート", "レポート", "Gen.", "-"],
    "I (formal)" : ["わたくし", "私 (formal)", "Gen.", "-"],
    "glad" : ["うれしい", "うれしい", "i - adj", "-"],
    "sad" : ["かなしい", "悲しい", "i - adj", "-"],
    "hot and spicy; salty" : ["からい", "辛い", "i - adj", "-"],
    "strict" : ["きびしい", "厳しい", "i - adj", "-"],
    "close; near" : ["ちかい", "近い", "i - adj", "-"],
    "various; different kinds of" : ["いろいろ", "いろいろ", "na - adj", "-"],
    "happy (lasting happiness)" : ["しあわせ", "幸せ", "na - adj", "-"],
    "no good" : ["だめ", "だめ", "na - adj", "-"],
    "to knit" : ["あむ", "編む", "u - verb", "～を"],
    "to lend; to rent" : ["かす", "貸す", "u - verb", "PにTを"],
    "to do one's best; to try hard" : ["がんばる", "頑張る", "u - verb", "-"],
    "to cry" : ["なく", "泣く", "u - verb", "-"],
    "to brush (teeth); to polish" : ["みがく", "磨く", "u - verb", "を"],
    "to keep a promise" : ["やくそくをまもる", "約束を守る", "u - verb", "-"],
    "to be moved/touched (by ...)" : ["かんどうする", "感動する", "irr - verb", "に"],
    "…times" : ["～かい", "回", "Numbers", "-"],
    "…kilometres;…kilograms" : ["～キロ", "", "Numbers", "-"],
    "(someone honorable) is present/home" : ["いらっしゃいます", "いらっしゃいます", "Gen.", "-"],
    "as a matter of fact, ..." : ["じつは", "実は", "Gen.", "-"],
    "all" : ["ぜんぶ", "全部", "Gen.", "-"],
    "my name is…" : ["～ともうします", "と申します", "Gen.", "-"],
    "one day" : ["いちにち", "一日 (duration)", "Numbers", "-"],
    "two days" : ["ふつか", "二日 (duration)", "Numbers", "-"],
    "three days" : ["みっか", "三日 (duration)", "Numbers", "-"],
    "four days" : ["よっか", "四日 (duration)", "Numbers", "-"],
    "five days" : ["いつか", "五日 (duration)", "Numbers", "-"],
    "six days" : ["むいか", "六日 (duration)", "Numbers", "-"],

    }


var_aaLesson_14 = {

    "stuffed animal (e.g., teddy bear)" : ["ぬいぐるみ", "ぬいぐるみ", "Gen.", "-"],
    "landlord; landlady" : ["おおやさん", "大家さん", "Gen.", "-"],
    "return (as a token of gratitude)" : ["おかえし", "お返し", "Gen.", "-"],
    "(your/his) wife" : ["おくさん", "奥さん", "Gen.", "-"],
    "uncle; middle-aged man" : ["おじさん", "おじさん", "Gen.", "-"],
    "aunt; middle-aged woman" : ["おばさん", "おばさん", "Gen.", "-"],
    "Christmas" : ["クリスマス", "クリスマス", "Gen.", "-"],
    "(your/her) husband" : ["ごしゅじん", "ごしゅじん", "Gen.", "-"],
    "tumbler; glass" : ["コップ", "コップ", "Gen.", "-"],
    "plate; dish" : ["さら", "皿", "Gen.", "-"],
    "time" : ["じかん", "時間", "Gen.", "-"],
    "ticket" : ["チケット", "", "Gen.", "-"],
    "chocolate" : ["チョコレート", "チョコレート", "Gen.", "-"],
    "sweat shirt" : ["トレーナー", "", "Gen.", "-"],
    "necktie" : ["ネクタイ", "ネクタイ", "Gen.", "-"],
    "St. Valentine's Day" : ["バレンタインデー", "バレンタインデー", "Gen.", "-"],
    "camcorder" : ["ビデオカメラ", "ビデオカメラ", "Gen.", "-"],
    "married couple; husband and wife" : ["ふうふ", "夫婦", "Gen.", "-"],
    "White Day (yet another gift-giving day)" : ["ホワイトデー", "ホワイトデー", "Gen.", "-"],
    "winter scarf" : ["マフラー", "マフラー", "Gen.", "-"],
    "comic book" : ["まんが", "漫画", "Gen.", "-"],
    "multistory apartment; condominium" : ["マンション", "マンション", "Gen.", "-"],
    "mandarin orange" : ["みかん", "みかん", "Gen.", "-"],
    "ring" : ["ゆびわ", "指輪", "Gen.", "-"],
    "radio" : ["ラジオ", "", "Gen.", "-"],
    "parents" : ["りょうしん", "両親", "Gen.", "-"],
    "resume" : ["りれきしょ", "履歴書", "Gen.", "-"],
    "to want" : ["ほしい", "欲しい", "i - adj", "-"],
    "stingy; cheap" : ["けち", "けち", "na - adj", "-"],
    "to send; to walk/drive (someone)" : ["おくる", "送る", "u - verb", "PにTを"],
    "to look good (on somebody)" : ["にあう", "似合う", "u - verb", "が"],
    "to give up" : ["あきらめる", "あきらめる", "ru - verb", "を"],
    "to give (to others)" : ["あげる", "あげる", "ru - verb", "PにTを"],
    "to give (me)" : ["くれる", "くれる", "ru - verb", "PにTを"],
    "to come into existence; to be made" : ["できる", "できる", "ru - verb", "が"],
    "to consult" : ["そうだんする", "相談する", "irr - verb", "Pに"],
    "to propose marriage" : ["プロポーズする", "プロポーズする", "irr - verb", "Pに"],
    "same" : ["おなじ", "同じ", "Gen.", "-"],
    "Mr./Mrs….(casual)" : ["～くん", "～君", "Gen.", "-"],
    "…like this; this kind of…" : ["こんな～", "", "Gen.", "-"],
    "[makes a noun plural]" : ["～たち", "", "Gen.", "-"],
    "we" : ["わたしたち", "私たち", "Gen.", "-"],
    "exactly" : ["ちょうど", "ちょうど", "Gen.", "-"],
    "what should one do" : ["どうしたらいい", "", "Gen.", "-"],
    "[generic counter for smaller items]" : ["こ", "個", "Numbers", "-"],
    "[counter for bound volumes]" : ["さつ", "冊", "Numbers", "-"],
    "[counter for equipment]" : ["だい", "台", "Numbers", "-"],
    "[counter for long objects]" : ["ほん", "本", "Numbers", "-"],
    "[counter for smaller animals]" : ["ひき", "匹", "Numbers", "-"],

    }





